[package]
name = "cat_control"
version = "0.1.0"
authors = ["arno"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.0.0"
libmath = "0.2.1"
[profile.dev]
debug=true